version: "3.8"
services:
  api:
    image: api
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    command: npm run dev
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
